version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres 
    container_name: my_postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=""
      - POSTGRES_DB=vectordb
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "vectordb"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  web:
    build:
      context: .
      dockerfile: Dockerfile.web  
    container_name: my_web_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: bash -c "./wait-for-it.sh postgres:5432 --timeout=300 --strict -- uvicorn main:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
